# 迭代器与生成器

迭代是Python最强大的功能之一，这是一种访问集合元素的方式。<br>
我们知道，通过列表生成式，我们可以直接创建一个列表，但是这个列表大小是有限的，但生成器(`generator`)将一边循环一边生成，甚至给出无限个数。<br>
在Python中，我们可以使用`for in`语句来完成迭代。

## 判断一个对象是否可以迭代

要判断对象是否可迭代，可以使用`collections.abc`中的`Iterable`类型来判断
```py
>>> from collections.abc import Iterable
>>> isinstance("abc",Iterable)
True
>>> isinstance([1,2,3],Iterable)
True
>>> isinstance(123,Iterable)
False
```

## 创建一个迭代器

可以使用`iter()`函数来创建一个迭代器，可以使用`next()`方法来遍历一个迭代器
```py
>>> i = iter([1,2,3])
>>> type(i)
<class 'list_iterator'>
>>> next(i)
1
>>> next(i)
2
>>> next(i)
3
>>> next(i)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration
```
`StopIteration`是迭代结束的标志，当出现`StopIteration`错误的时候，就说明迭代器已经完成迭代了<br>
但难道每次迭代我们都需要使用若干个`next()`函数吗？其实Python已经给我们准备好了，那就是`for in`循环，使用`for in`循环可以遍历一个迭代器，并且它可以处理好`StopIteration`错误，实际上，当我们使用`for in`遍历可迭代对象（比如`list`,`tuple`）的时候，都是先用这个可迭代对象生成一个迭代器，然后对迭代器进行迭代

## 创建生成器

要创建一个生成器，只需要将列表生成式的`[]`改成`()`
```py
>>> g = (x*x for x in range(10))
>>> g
<generator object <genexpr> at 0x0000028392CB9A10>
```
生成器也是一个迭代器，因此所以要访问生成器的元素，只要使用`next()`函数或者使用`for in`循环

```py
>>> g = (x*x for x in range(5))
>>> next(g)
0
>>> next(g)
1
>>> next(g)
4
>>> next(g)
9
>>> next(g)
16
>>> next(g)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration
```
```py
>>> g = (x*x for x in range(5))
>>> for i in g:
...     print(i)
...
0
1
4
9
16
```

## 生成器函数

除了使推导式，我们还可以使用`yield`使一个函数变成生成器函数

这是一个打印斐波那契数列的函数
```py
>>> def fib(c):
...     a,b = 0,1
...     while(c>0):
...         print(b)
...         a,b = b,a+b
...         c -= 1
...
>>> fib(5)
1
1
2
3
5
```
这个函数每次执行到`print(b)`便输出一个值，于是我们便把`print(b)`写成`yield b`，这样，我们便创建了一个generator函数，每次调用这个函数都会生成并返回一个生成器

`yield`就如同这个函数的一个断点，每当函数执行到`yield`的时候，便会停下来，当有`next()`函数调用的时候，把这个值递出去并进入下一轮循环，直到重新遇到`yield`并停下来

```py
>>> def fib(c):
...     a,b = 0,1
...     while(c>0):
...         yield b     #当函数执行到这里的时候便停下来等next()
...         a,b = b,a+b
...         c -= 1
...
>>> g = fib(5)
>>> for i in g:         #for in循环会处理好StopIteration错误
...     print(i)
...
1
1
2
3
5
```

但是如果想要获取这个函数的返回值怎么办呢

```py
>>> def f():
...     yield 2
...     yield 3
...     return 0
...
>>> g = f() 
>>> next(g) 
2
>>> next(g)
3
>>> next(g)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration: 0
```
可以看到，返回值会随着`StopIteration`错误被带出，因此想要获取函数返回值的话，就需要使用`try-except`语句